namespace CryptoFile.Client.Mapi
{
	internal enum MapiResult
	{
		SUCCESS_SUCCESS = 0,
		MAPI_E_USER_ABORT = 1,
		MAPI_E_FAILURE = 2,
		MAPI_E_LOGON_FAILURE = 3,
		MAPI_E_DISK_FULL = 4,
		MAPI_E_INSUFFICIENT_MEMORY = 5,
		MAPI_E_ACCESS_DENIED = 6,
		MAPI_E_TOO_MANY_SESSIONS = 8,
		MAPI_E_TOO_MANY_FILES = 9,
		MAPI_E_TOO_MANY_RECIPIENTS = 10,
		MAPI_E_ATTACHMENT_NOT_FOUND = 11,
		MAPI_E_ATTACHMENT_OPEN_FAILURE = 12,
		MAPI_E_ATTACHMENT_WRITE_FAILURE = 13,
		MAPI_E_UNKNOWN_RECIPIENT = 14,
		MAPI_E_BAD_RECIPTYPE = 15,
		MAPI_E_NO_MESSAGES = 16,
		MAPI_E_INVALID_MESSAGE = 17,
		MAPI_E_TEXT_TOO_LARGE = 18,
		MAPI_E_INVALID_SESSION = 19,
		MAPI_E_TYPE_NOT_SUPPORTED = 20,
		MAPI_E_AMBIGUOUS_RECIPIENT = 21,
		MAPI_E_MESSAGE_IN_USE = 22,
		MAPI_E_NETWORK_FAILURE = 23,
		MAPI_E_INVALID_EDITFIELDS = 24,
		MAPI_E_INVALID_RECIPS = 25,
		MAPI_E_NOT_SUPPORTED = 26,
		MAX_VALUE
	}
}